export const LOGIN_USER = 'LOGIN_USER';
export const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES';
export const SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS';
export const SEARCH_REPOSITORIES_FAILURE = 'SEARCH_REPOSITORIES_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';