export const LOGIN_USER = 'LOGIN_USER';
export const LOAD_REPOSITORIES = 'LOAD_REPOSITORIES';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';